### ISSUE TITLE
Home page displays all posts on the site, rather than filtering them by who you follow

### ISSUE THREAD

**Issue by calvinbrinkman30** [UltramanKiryu/Group-4#17]

**Comment by lchristopher99** [comment]
This can be fixed once a friends list property is added to the Profile model. By chaining filters, we can get all posts for current user and for each user in friends list.

(views.py/index) Something like:
// get all current user posts
posts = Post.objects.filter(user=user_object.username) 

// append post objs from each friend to posts variable
for friend in user_object.friends_list:
      posts += Post.objects.filter(user=friend.username)

**Comment by lchristopher99** [comment]
Fixed in commit:

https://github.com/UltramanKiryu/Group-4/commit/75a5804331972b81fbe98ece7b30f50abc23a12b

**Comment by UltramanKiryu** [comment]
fixed comment feature
