### ISSUE TITLE
Upon reaching a certain amount of posts, older posts begin to grow in size and take up much of the screen.

### ISSUE THREAD

**Issue by MuffinOnLoL** [UltramanKiryu/Group-4#6]
After reaching 3-4 posts, the image size begins to grow and takes up most of the width of the screen. Issue only occurs after reaching the listed threshold.

**Comment by lchristopher99** [comment]
Fixed in commit:

https://github.com/UltramanKiryu/Group-4/commit/75a5804331972b81fbe98ece7b30f50abc23a12b
